### ISSUE TITLE
post-thumbnail文章摘要左侧的缩略图

### ISSUE THREAD

**Issue by loglife** [unnamed42/hexo-theme-kunkka#1]
@unnamed42请问,主页里显示的文章摘要左侧的缩略图如何设置?我在post.md文章文件 里添加thumbnail:thumbnailurl但是图片显示不出来,而且在手机屏幕上显示网页该处会发生内容重叠

**Comment by unnamed42** [comment]
已尝试修复了一下，你更新之后再试试

**Comment by loglife** [comment]
可以正常显示了,非常感谢@unnamed42.

**Comment by loglife** [comment]
可以正常显示了,非常感谢@unnamed42.
